# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CRON_SEND

on:
  schedule:
    - cron:  '00 15 * * 1-5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven
      run: mvn package
    - name: Run
      #ここをバージョンで変えなきゃいけない
      run: java -jar target/LINEBOT_HandaSchoolLunch-1.0.0.jar
